### ISSUE TITLE
Collection of built-in formats

### ISSUE THREAD

**Issue by alexreg** [slog-rs/stream#2]
It would be nice to include a collection of built-in implementations of `Format`, for standard scenarios. Is there any format you recommend right now for general file logging? Perhaps one similar to what *slog-term* uses? Thanks.

**Comment by dpc** [comment]
I'm not aware of any standard text logging format. I don't think people care that much. If anyone needs a standard they will use json/bunyan, xml or something like that.

**Comment by alexreg** [comment]
Well, I just want something to log to a dedicated log file… not the system log. I’ll check out bunyan maybe!

**Comment by alexreg** [comment]
I presume syslog and journald only write to a single system log file?

**Comment by dpc** [comment]
A lot of users are using slog-term format and write it to a file. You can configure syslog and journald themselves to log into many places, I believe. But the slog crates provide facility to write to these daemons, not files directly.

**Comment by alexreg** [comment]
Got it. Thanks for the clarification.
